### PR TITLE
Prevent multiple call on helper functions in `AxesProxyHandler.update_request`. (#512)

### PR DESCRIPTION
**Pull request by hramezani**

### CODE REVIEW

**Comment by aleksihakli** [comment]
Just a small adjustment needed on the naming before merging.

**Comment by hramezani** [comment]
> Just a small adjustment needed on the naming before merging.

Should we change the `updated`? What is your suggestion for the naming?

**Comment by aleksihakli** [comment]
@hramezani since all the other attributes are `axes_something`, I think `axes_updated` would be well suited.

**Comment by hramezani** [comment]
@aleksihakli, I changed it to `axes_updated`.

**Comment by aleksihakli** [comment]
Great, upstreaming :)

**Comment by aleksihakli** [comment]
Released in version 5.0.19 on PyPI.

**Pull request merged**
