### PR TITLE
Bug: Add missing migrations

### PR DESCRIPTION
**Pull request by markddavidoff**
I also added a test to make sure this doesn't happen again.

Also if 4.4.1 is released without this, people will get migration issues.

### CODE REVIEW

**Comment by markddavidoff** [comment]
@aleksihakli @camilonova

**Comment by markddavidoff** [comment]
Its been a hot sec, I'm merging this.

**Comment by aleksihakli** [comment]
Great, good job on the regression test as well.

**Comment by jsharpe** [comment]
Looks like the version of 4.4.1 that got pushed to pypi didn't include this patch so its missing migrations. Can a 4.4.2 release be pushed to pypi to resolve this please?

**Pull request merged**
