### PR TITLE
fix duplicated AccessAttempts

### PR DESCRIPTION
**Pull request by PetrDlouhy**
fix for #788 

This prevents duplicated AccessAttempt objects to be created, also it deletes those duplicated attempts that are already present during the migration.

### CODE REVIEW

**Comment by aleksihakli** [comment]
@camilonova @hramezani @okapies what do you think of the update for the uniqueness constraints here? Can the uniqueness break something? I'd like at least a few people to pitch their opinions in for this change.

**Comment by aleksihakli** [comment]
@PetrDlouhy the QA step is failing with the current configuration and needs to be fixed before upstreaming.

**Comment by okapies** [comment]
I forgot the uniqueness setting… Thanks for the fix!

**Comment by aleksihakli** [comment]
Still needs stylistic fixes for the style checker to pass:

image

**Review by aleksihakli — APPROVED** [review]
LGTM!

**Pull request merged**
