### PR TITLE
Optional callable in settings to clean username

### PR DESCRIPTION
**Pull request by jaadus**
Related issue: #318

Add a setting to supply a callable that can return a correct username given a request object.
This can modify or clean it in case the supplied username in the post body does not match what goes into credentials. More about the problem this is solving in the issue.

### CODE REVIEW

**Comment by jorrit-wehelp** [comment]
Was looking into doing something similar, you beat me to it.
Only think I would suggest doing different is having the setting have a default value instead of None, pointing to a function that does the backward compatible AXES_USERNAME_FORM_FIELD getter.
This make it always go through the same path and the default implementation serves as an example to be overriden by users.

**Comment by jaadus** [comment]
In that case, I'd still have to go through another method to handle the `None` case as I do currently, in the util `get_client_username`, to protect against clients that override the setting explicitly to equal `None`, or add another check in `AppConfig.ready` before starting, which I would really like to avoid.

So your proposed change would just add a method that does the exact same thing as the default case in `utils.py` line 75 and set that method as the initial settings value instead of `None`. I can do that, but I don't really see any added value.

**Comment by camilonova** [comment]
Looks great. Thank you.
Please add some documentation on how this feature work.

**Comment by camilonova** [comment]
Awesome. Thanks!

**Comment by jd-cape** [comment]
Thanks for the merge!

What's the process for getting a 4.4 version out with these changes?

**Comment by camilonova** [comment]
I'll cut a release ASAP

**Pull request merged**
