### PR TITLE
Fix #299 #302

### LINKED ISSUE #299: Possible bug in signals.py?
https://github.com/jazzband/django-axes/blob/master/axes/signals.py#L59

Should the following:
```
        for attempt in attempts:
            failures = max(failures, attempt.failures_since_start)
```

be modified to:
```
        for attempt in attempts:
            failures += attempt.failures_since_start
```

Given that settings.AXES_ONLY_USER_FAILURES maybe return multiple attempts from the same user (different path or data). Wouldn't it make sense for all failed attempts to be summed together?  🤔 💭 

Thanks!

### PR DESCRIPTION
**Pull request by charleswhchan**
Added a new option AXES_USE_CACHE to workaround the issue with LocMemCache.
Enables axes to bypass the cache.

Perhaps this is a better solution than #305? Looking forward to the feedback. 😃

### CODE REVIEW

**Comment by aleksihakli** [comment]
Need some time to review this work. There might be more places where caching is used and those should be revised as well. Thank you for looking into this so quickly!

**Comment by charleswhchan** [comment]
Sure. Looking forward to the feedback 👍

**Comment by aleksihakli** [comment]
I'm not sure how necessary this changeset is #307. It should check for LocMemCache being used in the setup phase and fail configuration of `axes` altogether. A more important thing would be to add the option for disabling caches altogether.

**Comment by charleswhchan** [comment]
Thanks @aleksihakli. I am happy to see a better solution.

I did examine #307 in detail, but it seems like it provides an option to allow the axes cache to be set independently from the rest of Django -- ie. to DummyCache. In this case, it will effectively resolve the issue with #209 and #302 (sort of).

**Pull request closed without merging**
