### PR TITLE
Russian locale

### PR DESCRIPTION
**Pull request by lubicz-sielski**
Add russian locale files

### CODE REVIEW

**Comment by RDIL** [comment]
Ready after the CI passes.

**Comment by aleksihakli** [comment]
Hey @rdil! It would be nice to reserve a chance and a reasonable time window for contributors to look at the changes before merging and releasing them into upstream. Anyhow, thank you for the translation effort and the release.

**Comment by RDIL** [comment]
K

**Comment by jezdez** [comment]
@RDIL Thanks again for your contribution, but I mentioned in my mail, please don't merge PRs that you haven't reviewed yourself. In case of locale files it's usually appropriate to have a native speaker check if the translations are good. Since I'm not sure if that happened here, please be advised to look out for such things in the future. Thank you.

@aleksihakli Note, I've also noted @RDIL's merge behavior in other Jazzband repos and asked them to go through [all of their commits](https://github.com/RDIL?tab=overview&from=2018-12-01&to=2018-12-31&org=jazzband) and revert them if no actual review has happened. It's not okay that blind merges like this happen.

**Comment by RDIL** [comment]
@jezdez I'm sorry.  
It seems that I have made too many mistakes in this organization, and for the greater good I am removing myself, effective immediately.  Thanks for having me.

**Pull request merged**
