### PR TITLE
WP: Cache failures in cache

### PR DESCRIPTION
**Pull request by jorlugaqui**
Still a lot of pending tasks:

- Check / Add test
- Update models / signals
- Update command line tasks
- Manually tests

### CODE REVIEW

**Comment by camilonova** [comment]
Tests are failing

**Comment by jorlugaqui** [comment]
Yes, as I said there are some pending task, I will work on this soon

**Comment by jorlugaqui** [comment]
Hey Guys,

I have worked a little bit again, tests are working now and also I have covered python3. I guess what I should do now is:

+ To add new test for caching.
+ To add caching workflow in management commands / signals / models.

**Comment by jorlugaqui** [comment]
Ok, I have finished my pending tasks, let me know your thoughts.

**Comment by camilonova** [comment]
Looks good to me.

@aclark4life What do you think?

**Comment by aclark4life** [comment]
@camilonova I'm of the "merge now ask questions later" school :-D That said, looks like just some signals added? Probably fine …

**Pull request merged**
